// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sk.jazzman.buildingreporter.domain.building;

import org.springframework.beans.factory.annotation.Configurable;
import sk.jazzman.buildingreporter.domain.building.BType;

privileged aspect BType_Roo_Configurable {
    
    declare @type: BType: @Configurable;
    
}
